language: php
php:
  - 5.6
addons:
  code_climate:
    repo_token: 6ef3a2f4921d74dda426fbce9366e16351c6a3643cb35cd989039c0eb91fdf68
install:
  - composer install
script:
  - php travis-memcache-test.php
  - phpunit --configuration phpunit.xml
after_script:
  - bash bin/code-climate-test-reporter.sh
  - php bin/ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
