language: php
install:
  - composer install
php:
  - "5.5"
  - "5.6"
addons:
  code_climate:
    repo_token: 6ef3a2f4921d74dda426fbce9366e16351c6a3643cb35cd989039c0eb91fdf68
script:
  - phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
after_script:
  - vendor/bin/test-reporter
